language: python
python: 2.7
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=pypy
  - TOXENV=docs
install:
  - pip install tox
before_script:
  - python internal/generate.py
script:
  - tox
